### ISSUE TITLE
KeyError: 'values' - verbrauch_data = api.verbrauch(date_to_fetch)['values']

### ISSUE THREAD

**Issue by spinnaker1** [platysma/vienna-smartmeter#173]
Since yesterday, 2023-11-09, the applications crashes with following error:

```
Traceback (most recent call last):
File "/app/./main.py", line 68, in <module>
     verbrauch_data = api.verbrauch(date_to_fetch)['values']
KeyError: 'values'
```

Did they made any changes to the API?

**Comment by ghhausi** [comment]
Same issue here:
- I can login/authenticate
- I get the "Zaehlpunktnummer"
- but e.g. sending the URL _https://api.wstw.at/WN_SMART_METER_PORTAL_APIB2C/1.0/messdaten/zaehlpunkt/xx(=meinZählpunkt)/verbrauchRaw?dateFrom=2023-11-07T00%3A00%3A00.00Z&dateTo=2023-11-08T00%3A00%3A00.00Z&granularity=DAY_
- does give you a "**404**" !

**Help wanted!**

**Comment by ghhausi** [comment]
Analysis: It seems they have changed the API slightly
For the GET-requests the original URL was like:

https://api.wstw.at/WN_SMART_METER_PORTAL_API_B2C/1.0/messdaten/**zaehlpunkt**/nnn(=meinZählpunkt)/verbrauchRaw? ......
note the part "messdaten/zaehlpunkt/AT001......"  <-- there is the string "zaehlpunkt"

If I am correct, they have replaced "zaehlpunkt" with your actual customer number (should be part of the profile ?)
the new URL format is:
https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/messdaten/**1200888888**/AT0010000000000000001000001111111/verbrauch? ....... 

I will try to do further tests on my side on the weekend
best regards
Gerhard
BTW: this is not my actual customer number and zaehlpunkt :-)

**Comment by ghhausi** [comment]
My Solution: in "**vienna_smartmeter.py**" I defined

```
   def customerid(self):
        """Returns 'geschaeftspartner' = CustomerID for currently logged in user."""
        return self._call_api_wn("w/user/profile")["defaultGeschaeftspartnerRegistration"]["geschaeftspartner"]
```

and in "**_call_api_wstw**" I did insert 2 lines before making the request (self.session.request)

       if endpoint != "zaehlpunkte":                                # if the endpoint is NOT just "zaehlpunkte"
            url = url.replace("zaehlpunkt", self.customerid())      # we substitute the string "zaehlpunkt" with our customer-id
        response = self.session.request(method, url, headers=headers, json=data)

As you can see: I just replace "zaehlpunkt" with the customerid .... maybe there are more elegant ways - but works for me.
best regards
Gerhard

**Comment by fleinze** [comment]
Can confirm that this patch works

**Comment by spinnaker1** [comment]
@ghhausi Awesome! Maybe do a pull request? 👍

@platysma FYI

**Comment by fleinze** [comment]
a probably more elegant solution would be to fill in the customerid in the methods `verbrauch` and `verbrauch_raw` directly.
using the `customerid` method from @ghhausi 
replace 
`endpoint = "messdaten/zaehlpunkt/{}/verbrauchRaw".format(zaehlpunkt)`

with
`endpoint = "messdaten/{0}/{1}/verbrauchRaw".format(self.customerid(),zaehlpunkt)`

But I can't test this currently as the smartmeter-webportal is down for maintainance.

**Comment by fleinze** [comment]
The api is back online. Made a PR with a fix. Please try it.

**Comment by spinnaker1** [comment]
Doesn't work with mine.

**my app:**
```
# Import vienna-smartmeter module
from vienna_smartmeter import Smartmeter
from datetime import datetime, timedelta

# Smartmeter Credentials
username = '###'
password = '###'

api = Smartmeter(username, password)
print(api.profil()) # working

date_from_string = "2023-11-01T03:00:00.000000"
date_from = datetime.strptime(date_from_string, "%Y-%m-%dT%H:%M:%S.%f")

print(api.verbrauch_raw(date_from=date_from))
```


**Output:**
`{'quarter-hour-opt-in': False, 'statistics': {'maximum': 0, 'minimum': 0, 'average': 0}}`

Also, quarter-hour-opt-in:False is not true, because I opted in and checked in webportal.

**Comment by fleinze** [comment]
Your code works for me.

How did you install the new version?
I did it using
`pip install 'vienna-smartmeter @ git+https://github.com/fleinze/vienna-smartmeter.git'`

Also, I received such an output when the wstw-api was still offline today. Maybe there is still an error in the api, you should try again in a few hours.
